model_provider: "openai" # openai or ollama
model_name: "gpt-4-turbo"
temperature: 0.2
#max_tokens: null
embed_model_name: "text-embedding-ada-002"
embed_batch_size: 128
chunk_size: 1024
chunk_overlap: 128
